name: Deploy Hugo site to My Server

on:
  push:
    branches: [ main ] # 指定触发工作流的分支，例如 main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive # 如果主题是子模块，务必设置此项
          fetch-depth: 0

      # 2. 安装 Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest' # 建议固定特定版本，例如 '0.147.8'
          extended: true # 如果主题要求，请启用扩展版

      # 3. 构建网站 (生成的静态文件默认在 'public' 目录)
      - name: Build site with Hugo
        run: hugo --minify

      # 4. 部署到你的服务器
      - name: Deploy to Server via rsync
        uses: burnett01/rsync-deployments@7.0.1 # 一个常用的 rsync action
        with:
          switches: -avz --delete -e 'ssh -p 5222'
          path: ./public/ # 指定要同步的本地目录，即 Hugo 构建输出的目录
          remote_path: /root/app/hugo # 目标服务器上的目录
          remote_host: ${{ secrets.REMOTE_HOST }} # 你的服务器 IP 或域名
          remote_user: ${{ secrets.REMOTE_USER }} # SSH 登录用户名
          remote_key: ${{ secrets.REMOTE_PRIVATE_KEY }} # 私钥
